# A sample Gemfile
source "https://rubygems.org"

gem 'rubocop'
gem 'ruby-debug-ide'
gem 'debase'
gem 'rcodetools'
gem 'fastri'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'sinatra-activerecord'
gem 'rake'

gem 'bcrypt'

group :production do
 gem 'pg' , '~> 0.21.0'
end


group :development do
 gem 'sqlite3', '~> 1.4'
end

gem 'activerecord' , '5.2.3'
